global:
  name: consul
  datacenter: dc1
  image: hashicorp/consul-enterprise:1.18-ent
  enterpriseLicense:
    secretName: enterprise-license
    secretKey: key
  peering:
    enabled: true
  tls:
    enabled: true

connectInject:
  enabled: true
  default: true

meshGateway:
  enabled: true