global:
  name: consul
  datacenter: dc1
  tls:
    enabled: true
  # acls:
  #   manageSystemACLs: true

  image: ttl.sh/nathan-consul-ent-10:24h # hashicorppreview/consul-enterprise:1.18-dev
  imageK8S: hashicorppreview/consul-k8s-control-plane:1.4-dev-54714a40b9f5bcc27fa2b80e32fcc341d29160bf

  adminPartitions:
    enabled: true
    name: default  # required name for AP hosting consul-server

  enableConsulNamespaces: true

  enterpriseLicense:
    secretName: 'enterprise-license'
    secretKey: 'key'

  experiments:
  - resource-apis
  - v2tenancy

connectInject:
  default: true
  transparentProxy:
    defaultEnabled: true

meshGateway:
  enabled: true

ui:
  enabled: false

server:
  replicas: 3