global:
  name: consul
  datacenter: dc1
  tls:
    enabled: true
  # acls:
  #   manageSystemACLs: true

  image: ttl.sh/nathan-consul-ent-32:24h # hashicorppreview/consul-enterprise:1.18-dev
  imageK8S: hashicorppreview/consul-k8s-control-plane:1.4.0-dev-pr-87c07ed90aee3a0b887454a33bc5ec46a79ea229

  adminPartitions:
    enabled: true
    name: default  # required name for AP hosting consul-server

  enableConsulNamespaces: true

  enterpriseLicense:
    secretName: 'enterprise-license'
    secretKey: 'key'

  experiments:
  - resource-apis
  - v2tenancy

connectInject:
  default: true
  transparentProxy:
    defaultEnabled: true

meshGateway:
  enabled: true

ui:
  enabled: false

server:
  replicas: 3
