global:
  name: consul
  datacenter: dc1
  enabled: false
  tls:
    enabled: true
    caCert:
      secretName: consul-ca-cert # See step 6 from `Install Consul server cluster`
      secretKey: tls.crt
    caKey:
      secretName: consul-ca-key # See step 7 from `Install Consul server cluster`
      secretKey: tls.key
  # acls:
    # manageSystemACLs: true
    # bootstrapToken:
    #   secretName: consul-partitions-acl-token # See step 8 from `Install Consul server cluster`
    #   secretKey: token

  image: ttl.sh/nathan-consul-ent-32:24h # hashicorppreview/consul-enterprise:1.18-dev
  imageK8S: hashicorppreview/consul-k8s-control-plane:1.4.0-dev-pr-87c07ed90aee3a0b887454a33bc5ec46a79ea229

  adminPartitions:
    enabled: true
    name: other

  enableConsulNamespaces: true
  
  enterpriseLicense:
    secretName: 'enterprise-license'
    secretKey: 'key'

  experiments:
  - resource-apis
  - v2tenancy

externalServers:
  enabled: true
  tlsServerName: server.dc1.consul
  hosts: ['104.196.4.148']
  k8sAuthMethodHost: 'https://34.138.151.56'
  skipServerWatch: true
  
connectInject:
  default: true

meshGateway:
  enabled: true

ui:
  enabled: false
