apiVersion: consul.hashicorp.com/v1alpha1
kind: ExportedServices
metadata:
  name: other
spec:
  services:
    - name: destination
      namespace: default
      consumers:
        - partition: default
    - name: mesh-gateway
      namespace: default
      consumers:
        - partition: default
