global:
  name: consul
  datacenter: dc1
  metrics:
    enabled: true
    enableGatewayMetrics: true
  imageConsulDataplane: consul-dataplane:local

connectInject:
  enabled: true
  defaultEnabled: true
  defaultEnableMerging: true

ingressGateways:
  enabled: true
  logLevel: debug
  defaults:
    service:
      type: ClusterIP