global:
  name: consul
  datacenter: dc1
  metrics:
    enabled: true
    enableGatewayMetrics: true

connectInject:
  enabled: true
  defaultEnabled: true
  defaultEnableMerging: true

ingressGateways:
  enabled: true
  logLevel: debug
  defaults:
    service:
      type: LoadBalancer