apiVersion: consul.hashicorp.com/v1alpha1
kind: ExportedServices
metadata:
  name: default
spec:
  services:
  - name: frontend
    consumers:
    - samenessGroup: frontends
  - name: backend
    consumers:
    - samenessGroup: frontends