apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: backend
      annotations:
        consul.hashicorp.com/mesh-inject: "true"
    spec:
      serviceAccountName: backend
      containers:
      - name: backend-8080
        image: nicholasjackson/fake-service:v0.26.0
        ports:
        - containerPort: 8080
        env:
        - name: LISTEN_ADDR
          value: "0.0.0.0:8080"
        - name: NAME
          value: backend-8080
      - name: backend-9090
        image: nicholasjackson/fake-service:v0.26.0
        ports:
        - containerPort: 9090
        env:
        - name: LISTEN_ADDR
          value: "0.0.0.0:9090"
        - name: NAME
          value: backend-9090
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 8080
      name: "8080"
    - port: 9090
      name: "9090"
