apiVersion: mesh.consul.hashicorp.com/v2beta1
kind: MeshGateway
metadata:
  name: mesh-gateway
  namespace: consul
spec:
  gatewayClassName: consul-mesh-gateway
  listeners:
  - name: wan
    port: 8080
