global:
  name: consul
  datacenter: dc1
  peering:
    enabled: true
  tls:
    enabled: true
  acls:
    manageSystemACLs: true

  image: hashicorp/consul-enterprise:1.17-ent

  adminPartitions:
    enabled: true
    name: default  # required name for AP hosting consul-server

  enableConsulNamespaces: true

  enterpriseLicense:
    secretName: 'enterprise-license'
    secretKey: 'key'

connectInject:
  default: true
  transparentProxy:
    defaultEnabled: true

meshGateway:
  enabled: true

ui:
  enabled: true
  service:
    enabled: true
    type: LoadBalancer
