global:
  name: consul
  datacenter: dc1
  enabled: false
  peering:
    enabled: true
  tls:
    enabled: true
    caCert:
      secretName: consul-ca-cert # See step 6 from `Install Consul server cluster`
      secretKey: tls.crt
    caKey:
      secretName: consul-ca-key # See step 7 from `Install Consul server cluster`
      secretKey: tls.key
  acls:
    manageSystemACLs: true
    bootstrapToken:
      secretName: consul-partitions-acl-token # See step 8 from `Install Consul server cluster`
      secretKey: token

  image: hashicorp/consul-enterprise:1.17-ent

  adminPartitions:
    enabled: true
    name: other

  enableConsulNamespaces: true
  
  enterpriseLicense:
    secretName: 'enterprise-license'
    secretKey: 'key'

externalServers:
  enabled: true
  tlsServerName: server.dc1.consul
  hosts: ['34.74.84.177']
  k8sAuthMethodHost: 'https://34.23.167.200'
  
connectInject:
  default: true
  transparentProxy:
    defaultEnabled: true

meshGateway:
  enabled: true

ui:
  enabled: true
  service:
    enabled: true
    type: LoadBalancer
