global:
  name: consul
  datacenter: dc2
  peering:
    enabled: true
  tls:
    enabled: true
    enableAutoEncrypt: true
  acls:
    manageSystemACLs: true
  
connectInject:
  default: true
  transparentProxy:
    defaultEnabled: true

meshGateway:
  enabled: true

terminatingGateways:
  enabled: true
  logLevel: debug

ui:
  enabled: true
  service:
    enabled: true
    type: LoadBalancer
