global:
  name: consul
  datacenter: dc1
  peering:
    enabled: true
  tls:
    enabled: true
    enableAutoEncrypt: true
  acls:
    manageSystemACLs: true

  
connectInject:
  default: true
  transparentProxy:
    defaultEnabled: true

meshGateway:
  enabled: true

ui:
  enabled: true
  service:
    enabled: true
    type: LoadBalancer
