global:
  name: consul
  datacenter: dc1
  image: hashicorp/consul-enterprise:1.19-ent
  enableConsulNamespaces: true
  enterpriseLicense:
    secretName: license
    secretKey: license
  
connectInject:
  enabled: true
  consulNamespaces:
    mirroringK8S: true
