apiVersion: v1
kind: ServiceAccount
metadata:
  name: destination
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: destination
  namespace: default
spec:
  selector:
    matchLabels:
      app: destination
  replicas: 3
  template:
    metadata:
      labels:
        app: destination
      annotations:
        consul.hashicorp.com/mesh-inject: "true"
    spec:
      serviceAccountName: destination
      containers:
      - name: destination-8080
        image: nicholasjackson/fake-service:v0.26.0
        ports:
        - name: "hello8080"
          containerPort: 8080
        env:
        - name: LISTEN_ADDR
          value: "0.0.0.0:8080"
        - name: NAME
          valueFrom:
            fieldRef:
              fieldPath: 'metadata.name'
        - name: MESSAGE
          value: 'Hello from the other partition, port 8080!'
      - name: destination-9090
        image: nicholasjackson/fake-service:v0.26.0
        ports:
        - name: "hello9090"
          containerPort: 9090
        env:
        - name: LISTEN_ADDR
          value: "0.0.0.0:9090"
        - name: NAME
          valueFrom:
            fieldRef:
              fieldPath: 'metadata.name'
        - name: MESSAGE
          value: 'Hello from the other partition, port 9090!'
---
apiVersion: v1
kind: Service
metadata:
  name: destination
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: destination
  ports:
    - port: 8080
      name: "hello8080"
    - port: 9090
      name: "hello9090"
