apiVersion: v1
kind: Service
metadata:
  labels:
    app: source
  name: source
  namespace: default
spec:
  ports:
  - port: 8080
  selector:
    app: source
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: source
  namespace: default
automountServiceAccountToken: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: source
  name: source
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: source
  template:
    metadata:
      labels:
        app: source
      annotations:
        consul.hashicorp.com/mesh-service-destinations: '8080.port.destination.svc.default.ns.other.ap:1234,9090.port.destination.svc.default.ns.other.ap:5678'
    spec:
      serviceAccountName: source
      containers:
      - name: source
        image: leodotcloud/swiss-army-knife:latest
        command: ["/bin/sleep", "3650d"]
      - name: hello
        image: nicholasjackson/fake-service:v0.26.0
        ports:
        - containerPort: 8080
        env:
        - name: LISTEN_ADDR
          value: "0.0.0.0:8080"
        - name: NAME
          value: source-8080
