apiVersion: consul.hashicorp.com/v1alpha1
kind: MeshService
metadata:
  name: backend
  namespace: default
spec:
  name: backend # The name of the Consul service
  # peerName: dc2 # The name of the peer exporting the Consul service