apiVersion: v1
kind: Pod
metadata:
  name: privileged-hello
  namespace: consul
  labels:
    app: hello-world
  annotations:
    # This annotation documents that we're intentionally testing PSA
    seccomp.security.alpha.kubernetes.io/pod: "runtime/default"
spec:
  containers:
  - name: hello
    image: gcr.io/google-samples/hello-app:1.0
    # Security context that should trigger PSA baseline policy
    securityContext:
      allowPrivilegeEscalation: false
      # Additional privileged settings that violate baseline
      capabilities:
        add: ["NET_BIND_SERVICE"]
        # drop: ["ALL"]
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    ports:
    - containerPort: 8080
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"
  # Setting an explicit security context at pod level as well
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault