apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: to-backend-default
  namespace: default
spec:
  destination:
    name: backend
  sources:
    - name: api-gateway
      peer: dc1
      action: allow
