global:
  name: consul
  datacenter: dc1

  tls:
    enabled: true
    enableAutoEncrypt: true
  
  acls:
    manageSystemACLs: true

connectInject:
  enabled: true
  apiGateway:
    manageExternalCRDs: false

apiGateway:
  enabled: true
  image: hashicorp/consul-api-gateway:0.5.5