apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: servicea
  namespace: default
spec:
  protocol: http
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: servicea
  name: servicea
  namespace: default
spec:
  ports:
  - port: 8080
  selector:
    app: servicea
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: servicea
  namespace: default
automountServiceAccountToken: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: servicea
  name: servicea
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicea
  template:
    metadata:
      labels:
        app: servicea
      annotations:
        'consul.hashicorp.com/connect-service-upstreams': 'external:1234'
    spec:
      serviceAccountName: servicea
      containers:
      - name: servicea
        image: leodotcloud/swiss-army-knife:latest
        command: ["/bin/sleep", "3650d"]
