global:
  name: consul
  datacenter: dc2
  peering:
    enabled: true
  tls:
    enabled: true
  acls:
    manageSystemACLs: true

connectInject:
  enabled: true
  default: true

meshGateway:
  enabled: true