apiVersion: consul.hashicorp.com/v1alpha1
kind: TerminatingGateway
metadata:
  name: terminating-gateway
spec:
  services:
    - name: destination
      caFile: "/etc/ssl/certs/ca-certificates.crt"
      sni: "jsonplaceholder.typicode.com"
