apiVersion: v1
kind: Service
metadata:
  labels:
    app: bastion
  name: bastion
  namespace: default
spec:
  ports:
  - port: 8080
  selector:
    app: bastion
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bastion
  namespace: default
automountServiceAccountToken: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bastion
  name: bastion
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bastion
  template:
    metadata:
      labels:
        app: bastion
    spec:
      serviceAccountName: bastion
      containers:
      - name: bastion
        image: leodotcloud/swiss-army-knife:latest
        command: ["/bin/sleep", "3650d"]
