global:
  name: consul
  datacenter: dc1

  # image: hashicorp/consul-enterprise:1.18-ent
  # enterpriseLicense:
  #   secretName: license
  #   secretKey: license

  tls:
    enabled: true
    enableAutoEncrypt: true
  
  acls:
    manageSystemACLs: true

connectInject:
  enabled: true
  apiGateway:
    managedGatewayClass:
      serviceType: NodePort
